name: atmakitchen_4_j_mobile
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_carousel_slider: ^1.1.0
  flutter_login: ^5.0.0
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.5
  http: ^1.2.0
  shared_preferences: ^2.2.3
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  firebase_messaging: ^14.9.4
  firebase_analytics: ^10.10.7
  firebase_core: ^2.32.0
  awesome_notifications: ^0.7.4+1
  flutter_month_picker: ^0.0.2


dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/roti/
    - images/cake/
    - images/hampers/
    - images/minuman/
