// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9PQZyDNeNKTaLHNXBPybGTG_9lmTSYYE',
    appId: '1:144137073821:web:cafe4beace9157e4d65074',
    messagingSenderId: '144137073821',
    projectId: 'atmakitchen4',
    authDomain: 'atmakitchen4.firebaseapp.com',
    storageBucket: 'atmakitchen4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS_PyahWR8Gu7lXktpUqqBAzgJbcz7zwU',
    appId: '1:144137073821:android:0f425ae7c815295ed65074',
    messagingSenderId: '144137073821',
    projectId: 'atmakitchen4',
    storageBucket: 'atmakitchen4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYmhG8oZzUqdTGa0eNp6zPLdF9gZLU12w',
    appId: '1:144137073821:ios:bf7ab994c9d2baa5d65074',
    messagingSenderId: '144137073821',
    projectId: 'atmakitchen4',
    storageBucket: 'atmakitchen4.appspot.com',
    iosBundleId: 'com.example.atmakitchen4JMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYmhG8oZzUqdTGa0eNp6zPLdF9gZLU12w',
    appId: '1:144137073821:ios:bf7ab994c9d2baa5d65074',
    messagingSenderId: '144137073821',
    projectId: 'atmakitchen4',
    storageBucket: 'atmakitchen4.appspot.com',
    iosBundleId: 'com.example.atmakitchen4JMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9PQZyDNeNKTaLHNXBPybGTG_9lmTSYYE',
    appId: '1:144137073821:web:c8ae00f8fc566aabd65074',
    messagingSenderId: '144137073821',
    projectId: 'atmakitchen4',
    authDomain: 'atmakitchen4.firebaseapp.com',
    storageBucket: 'atmakitchen4.appspot.com',
  );
}
